#!/usr/bin/env php
<?php

/**
 * Generator
 *
 * @link [sugeng-sulistiyawan.github.io](sugeng-sulistiyawan.github.io)
 * @author Sugeng Sulistiyawan <sugeng.sulistiyawan@gmail.com>
 * @copyright Copyright (c) 2023
 */

use app\Config;

$root = __DIR__;

require $root . '/vendor/autoload.php';
require $root . '/vendor/yiisoft/yii2/Yii.php';
require $root . '/helpers/function.php';

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'prod');

$config = new Config();

foreach ([
    'index',
] as $page) {
    echo "build {$page} ...";
    try {
        build($config, $page);
    } catch (\Throwable $th) {
        echo " error\n";
        exit;
    }
    echo " success\n";
}
