#!/usr/bin/env php
<?php

/**
 * Generator
 *
 * @link [sugeng-sulistiyawan.github.io](sugeng-sulistiyawan.github.io)
 * @author Sugeng Sulistiyawan <sugeng.sulistiyawan@gmail.com>
 * @copyright Copyright (c) 2023
 */

use app\Config;

$root = __DIR__;

require $root . '/vendor/autoload.php';
require $root . '/vendor/yiisoft/yii2/Yii.php';
require $root . '/helpers/function.php';

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'prod');

$config = new Config();

// $baseUrl = 'https://kaderkerensmpn5trenggalek.my.id';
$baseUrl = '';

$pages = [
    'index',
    'dokumentasi',
    'tentang',
    'inovasi',
    'data-hasil',
];
$replace = [
    $config->baseUrl              => $baseUrl . '/',
    $config->assets               => './assets',
    '/index.php?page=index'       => 'index.html',
    '/index.php?page=dokumentasi' => 'dokumentasi.html',
    '/index.php?page=tentang'     => 'tentang.html',
    '/index.php?page=inovasi'     => 'inovasi.html',
    '/index.php?page=data-hasil'  => 'data-hasil.html',
];
foreach ($pages as $page) {
    echo "build {$page} ...";
    try {
        $content = file_get_contents($config->baseUrl . '/index.php?prod=1&page=' . $page);

        $html = strtr($content, $replace);

        file_put_contents(dirname($config->root) . '/' . $page . '.html', $html);
    } catch (\Throwable $th) {
        echo " error\n{$th->getMessage()}";
        exit;
    }
    echo " success\n";
}
